### ISSUE TITLE
Player fastSeekedAudio make audio sources bouncing

### ISSUE THREAD

**Issue by tangshuang** [redotvideo/revideo#290]
When I use player bundle in browser, I found the audio bouncing, for example, when the audio playing:

"I said, you are smart."

It plays like:

"I said, you ar..you are smart."

After I comment out the sentence `this.setCurrentTime(time);` in fastSeekedAudio method, it become normal.

```
        if (Math.abs(audio.currentTime - time) > 0.3) {
            // this.setCurrentTime(time);
        }
```

I know why and how it happens, but I could not fix it.
Someone look this, may help to fix this.

**Comment by justusmattern27** [comment]
@tangshuang thanks for reporting! This is a correction that makes sure audio is in sync with the actual playback. It seems like the threshold is a bit too small and causes problems in your case. I think we can increase the threshold a bit, which should fix it

**Comment by tangshuang** [comment]
> @tangshuang thanks for reporting! This is a correction that makes sure audio is in sync with the actual playback. It seems like the threshold is a bit too small and causes problems in your case. I think we can increase the threshold a bit, which should fix it

Thanks! This may be supported as a property of Audio component?

**Comment by hkonsti** [comment]
I think I would prefer to have this as a constant value that can't be changed. Ideally, we'll find a good threshold that works for everyone which then makes changing it pointless. Feel free to reopen if there are more questions.

**Comment by tangshuang** [comment]
> I think I would prefer to have this as a constant value that can't be changed. Ideally, we'll find a good threshold that works for everyone which then makes changing it pointless. Feel free to reopen if there are more questions.

However, I have try your solution, change to `if (Math.abs(audio.currentTime - time) > 1) {` but the problem still there.

**Comment by justusmattern27** [comment]
@tangshuang can you post the code here so that we can reproduce the issue?
